// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: CallMessage.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// method - name of method that should be called
// data - serialized protobuf message
type CallParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CallParameters) Reset() {
	*x = CallParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CallMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallParameters) ProtoMessage() {}

func (x *CallParameters) ProtoReflect() protoreflect.Message {
	mi := &file_CallMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallParameters.ProtoReflect.Descriptor instead.
func (*CallParameters) Descriptor() ([]byte, []int) {
	return file_CallMessage_proto_rawDescGZIP(), []int{0}
}

func (x *CallParameters) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallParameters) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// data - serialized protobuf return values message
// error - error message. Empty in case no error
type ReturnValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ReturnValue) Reset() {
	*x = ReturnValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CallMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnValue) ProtoMessage() {}

func (x *ReturnValue) ProtoReflect() protoreflect.Message {
	mi := &file_CallMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnValue.ProtoReflect.Descriptor instead.
func (*ReturnValue) Descriptor() ([]byte, []int) {
	return file_CallMessage_proto_rawDescGZIP(), []int{1}
}

func (x *ReturnValue) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReturnValue) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_CallMessage_proto protoreflect.FileDescriptor

var file_CallMessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x43, 0x61, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x3c, 0x0a, 0x0e, 0x43,
	0x61, 0x6c, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x37, 0x0a, 0x0b, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CallMessage_proto_rawDescOnce sync.Once
	file_CallMessage_proto_rawDescData = file_CallMessage_proto_rawDesc
)

func file_CallMessage_proto_rawDescGZIP() []byte {
	file_CallMessage_proto_rawDescOnce.Do(func() {
		file_CallMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_CallMessage_proto_rawDescData)
	})
	return file_CallMessage_proto_rawDescData
}

var file_CallMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_CallMessage_proto_goTypes = []any{
	(*CallParameters)(nil), // 0: common.CallParameters
	(*ReturnValue)(nil),    // 1: common.ReturnValue
}
var file_CallMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CallMessage_proto_init() }
func file_CallMessage_proto_init() {
	if File_CallMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CallMessage_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CallParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CallMessage_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CallMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CallMessage_proto_goTypes,
		DependencyIndexes: file_CallMessage_proto_depIdxs,
		MessageInfos:      file_CallMessage_proto_msgTypes,
	}.Build()
	File_CallMessage_proto = out.File
	file_CallMessage_proto_rawDesc = nil
	file_CallMessage_proto_goTypes = nil
	file_CallMessage_proto_depIdxs = nil
}
